name: Actions Workflow

on:
  push:
    branches:
      - main
      - "feature/*" # matches anything that starts with feature/
      - "!feature/ignore_me" #ignores this branch
    tags:
      - v1
    paths:
      - "**.js"
      - "!filename.js"
    # paths-ignore:
    #   - 'docs/**'
  # repository_dispatch:
  # types: [build]
  # schedule:
  #   - cron: "0/6 1 * * *"
  # pull_request:
  #   types: [closed, assigned, opened, reopned]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        #   git clone git@github:$GITHUB_REPOSITORY
        #   git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files after checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Jon Erik Ullvang
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
